import type { ReactNode } from "react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@vxture/design-ui";

// 三个动态维度 - GRAPHIC ONLY, label/value 挪进 tooltip (owner, 2026-09-21:
// 考虑三个板块，商机数量，客户级别，健康评估，都只提供一个图形化，文字作为
// tooltip，这个很清楚). 之前的骨架是"图形 + 两行文字"横向排开(2026-09-20 的
// 版本, 跟 mockup 的 `.health-mini` 一模一样), 但这三块后来从 header 的横排
// 挪进了侧栏卡片, 纵向堆叠时那两行文字撑出比图形本身还多的高度, 是这张卡
// "很错乱"的主要原因之一 - 三个图形(圆环/勋章/圆环)紧挨着才是真正紧凑的
// 读法, 细节留给 hover。tag.tsx 的 NameOverflowTag 已经是同一个"图形 +
// Tooltip"的组合, 这里复用同一个模式而不是发明第二种。
export function DimensionStat({
  figure,
  label,
  value,
}: {
  readonly figure: ReactNode;
  readonly label: ReactNode;
  readonly value: ReactNode;
}) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <div className="inline-flex">{figure}</div>
      </TooltipTrigger>
      <TooltipContent>
        <div className="text-[0.65rem] font-bold tracking-wide uppercase opacity-70">{label}</div>
        <div className="text-body-sm">{value}</div>
      </TooltipContent>
    </Tooltip>
  );
}

// 徽章区的圆币 (owner, 2026-09-24: 除了级别徽章，其他两个需要优化，最好是有
// png背景，三个整体都是圆形结构，有渐变色). The medal is a glossy PNG; the
// deals and health badges now sit on glossy gradient discs drawn to match it
// (public/assets/icons/coin-*.png, generated by scripts/assets/gen-badge-coins.py
// so they can be redrawn rather than hand-edited). White type on the disc,
// with a soft shadow so it holds on the light upper gloss.
//
// A NAMED CUSTOM STYLE, not a DS element restyled: the DS has no coin or
// medal; the owner allows own styles where it has no knob (2026-09-24).
const COIN_SIZE = 46;
const COIN_TEXT = "text-white [text-shadow:0_1px_2px_rgb(0_0_0/0.35)]";

function Coin({ src, children }: { readonly src: string; readonly children: ReactNode }) {
  return (
    <div
      className={`relative flex h-[2.875rem] w-[2.875rem] flex-none flex-col items-center justify-center rounded-full bg-cover ${COIN_TEXT}`}
      style={{ backgroundImage: `url(${src})` }}
    >
      {children}
    </div>
  );
}

/** 级别: the medal on a pale disc tinted like it (owner, 2026-09-24: 奖牌徽章
 *  也放进一个圆形中，与其他2个形状一致，背景色可以淡一些). */
export function TierCoin({ tier, medalSrc, label }: { readonly tier: "strategic" | "key" | "standard"; readonly medalSrc: string; readonly label: string }) {
  const bg = { strategic: "gold", key: "silver", standard: "bronze" }[tier];
  return (
    <div role="img" aria-label={label} className="inline-flex">
      <Coin src={`/assets/icons/coin-tier-${bg}.png`}>
        <img src={medalSrc} alt="" className="h-[1.875rem] w-auto drop-shadow-sm" />
      </Coin>
    </div>
  );
}

/** 健康度: the score on a disc whose colour follows it in 10-point steps -
 *  red, amber, green, deepening within each band, split on healthTone's own
 *  40 / 70 lines (owner, 2026-09-24: 根据健康分数，背景颜色进行改变). A thin
 *  white arc inside the rim is the gauge the old ScoreRing drew. */
export function HealthCoin({ score, label }: { readonly score: number; readonly label: string }) {
  const r = 18.5;
  const c = 2 * Math.PI * r;
  const clamped = Math.max(0, Math.min(100, score));
  const pct = clamped / 100;
  const step = String(Math.floor(clamped / 10)).padStart(2, "0");
  return (
    <div role="img" aria-label={label} className="relative inline-flex">
      <Coin src={`/assets/icons/coin-health-${step}.png`}>
        <span className="font-display text-base leading-none font-extrabold">{score}</span>
      </Coin>
      <svg
        width={COIN_SIZE}
        height={COIN_SIZE}
        viewBox={`0 0 ${COIN_SIZE} ${COIN_SIZE}`}
        aria-hidden="true"
        className="pointer-events-none absolute inset-0"
      >
        <circle cx={23} cy={23} r={r} fill="none" stroke="white" strokeOpacity={0.25} strokeWidth={2} />
        <circle
          cx={23}
          cy={23}
          r={r}
          fill="none"
          stroke="white"
          strokeOpacity={0.9}
          strokeWidth={2}
          strokeLinecap="round"
          strokeDasharray={`${c * pct} ${c}`}
          transform="rotate(-90 23 23)"
        />
      </svg>
    </div>
  );
}

// 徽章区的商机块 (owner, 2026-09-21: 商机数 / 累计合同额，分两行，浅色横线隔开，
// 商机数大字体，合同额小字体+淡色) - now on a round coin like the other two
// (2026-09-24). Its own Tooltip, a sister of DimensionStat: it has two
// label/value pairs, and one tooltip says one thing.
export function DealsSummaryBadge({
  count,
  countLabel,
  amountText,
  amountLabel,
  amountFullText,
  amountUnitText = null,
}: {
  readonly count: number;
  readonly countLabel: string;
  /** formatMoneyCompact 的结果 - 徽章正文只有这么大地方, 摆不下完整数字。
   *  null 表示这批开放商机没有一个能合并成同一币种的总额(混币种或全部
   *  未定价) - 这时只显示商机数, 不硬凑一个误导性的合计。 */
  readonly amountText: string | null;
  readonly amountLabel: string;
  /** formatMoney 的完整结果 - compact 之外的精确数字放 tooltip 里。 */
  readonly amountFullText: string | null;
  /** 单位与币种 (owner, 2026-09-24: 金额只显示数字) - the coin shows the bare
   *  figure, so what it counts in is said here. */
  readonly amountUnitText?: string | null;
}) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <div className="inline-flex">
          <Coin src="/assets/icons/coin-deals.png">
            <span className="font-display text-base leading-none font-extrabold">{count}</span>
            {amountText ? (
              <>
                <span className="my-[0.1875rem] h-px w-6 bg-white/50" />
                <span className="text-[0.6rem] leading-none font-bold opacity-90 tabular-nums">{amountText}</span>
              </>
            ) : null}
          </Coin>
        </div>
      </TooltipTrigger>
      <TooltipContent>
        <div className="text-[0.65rem] font-bold tracking-wide uppercase opacity-70">{countLabel}</div>
        <div className="text-body-sm">{count}</div>
        {amountFullText ? (
          <>
            <div className="text-[0.65rem] font-bold tracking-wide uppercase opacity-70 mt-2xs">{amountLabel}</div>
            <div className="text-body-sm">{amountFullText}</div>
            {amountUnitText ? <div className="text-body-sm opacity-80">{amountUnitText}</div> : null}
          </>
        ) : null}
      </TooltipContent>
    </Tooltip>
  );
}
